Make it easier to run studies from git checkouts (#235)
- When loading a builder, we add the study dir's parent folder
  into sys.path, so that builders can import helper code.
  This is basically equivalent to doing PYTHONPATH=. from a checkout.
- When searching for the study dir, and we find a manifest.toml,
  actually read the manifest to find the study_prefix instead of using
  the directory name for the study name. This allows more natural
  python package layouts (rather than `module_name/study_name`, you can
  just do `module_name`)

This also bumps ruff's version to 0.4.4 and has the commit hook just
auto-commit any formatting changes.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -48,7 +48,7 @@ jobs:
         run: |
           sqlfluff lint
       - name: Run ruff
-        if: success() || failure() # still run black if above checks fails
+        if: success() || failure() # still run ruff if above checks fails
         run: |
           ruff check
           ruff format --check
